


/*---------------------------------------------
 * assembled at: Thu Dec 26 2013 19:54:32 GMT+0400 (Московское время (зима))
 * directory: tests/common/game/RELEASE/
 * file: tests/common/game/game.ts
 * name: game
 *--------------------------------------------*/


'use strict';var akra;
(function(b){function G(b,c){return b.getManager().getEngine().getResourceManager().colladaPool.findResource(c).attachToScene(b)}function I(f){var c=T;c.buttons[b.EGamepadCodes.SELECT]=f.isKeyPress(b.EKeyCodes.ENTER);c.buttons[b.EGamepadCodes.START]=f.isKeyPress(b.EKeyCodes.G);c.buttons[b.EGamepadCodes.PAD_TOP]=f.isKeyPress(b.EKeyCodes.UP);c.buttons[b.EGamepadCodes.PAD_BOTTOM]=f.isKeyPress(b.EKeyCodes.DOWN);c.buttons[b.EGamepadCodes.PAD_LEFT]=f.isKeyPress(b.EKeyCodes.LEFT);c.buttons[b.EGamepadCodes.PAD_RIGHT]=f.isKeyPress(b.EKeyCodes.RIGHT);
c.buttons[b.EGamepadCodes.FACE_1]=f.isKeyPress(b.EKeyCodes.N5);c.buttons[b.EGamepadCodes.FACE_2]=f.isKeyPress(b.EKeyCodes.N6);c.buttons[b.EGamepadCodes.FACE_3]=f.isKeyPress(b.EKeyCodes.N7);c.buttons[b.EGamepadCodes.FACE_4]=f.isKeyPress(b.EKeyCodes.N8);c.buttons[b.EGamepadCodes.RIGHT_SHOULDER_BOTTOM]=f.isKeyPress(b.EKeyCodes.CTRL)?1:0;c.buttons[b.EGamepadCodes.LEFT_SHOULDER_BOTTOM]=f.isKeyPress(b.EKeyCodes.SHIFT)?1:0;var a=(f.isKeyPress(b.EKeyCodes.A)?-1:0)+(f.isKeyPress(b.EKeyCodes.D)?1:0),g=(f.isKeyPress(b.EKeyCodes.S)?
1:0)+(f.isKeyPress(b.EKeyCodes.W)?-1:0);c.axes[b.EGamepadAxis.LEFT_ANALOGUE_VERT]=g;c.axes[b.EGamepadAxis.LEFT_ANALOGUE_HOR]=a;a=(f.isKeyPress(b.EKeyCodes.NUMPAD4)?-1:0)+(f.isKeyPress(b.EKeyCodes.NUMPAD6)?1:0);g=(f.isKeyPress(b.EKeyCodes.NUMPAD5)?1:0)+(f.isKeyPress(b.EKeyCodes.NUMPAD8)?-1:0);c.axes[b.EGamepadAxis.RIGHT_ANALOGUE_VERT]=g;c.axes[b.EGamepadAxis.RIGHT_ANALOGUE_HOR]=a;return c}function U(f,c,a){var f=b.self.hero.camera,c=a.timeDelta,g=b.self.gamepads.find(0)||I(w);if(g&&f.isActive()){var e=
-g.axes[b.EGamepadAxis.RIGHT_ANALOGUE_HOR],h=-g.axes[b.EGamepadAxis.RIGHT_ANALOGUE_VERT];b.math.abs(e)<a.analogueButtonThreshold&&(e=0);b.math.abs(h)<a.analogueButtonThreshold&&(h=0);var g=a.cameraCharacterFocusPoint.add(b.self.hero.pelvis.worldPosition,b.Vec3.stackCeil.set()),p=f.localOrientation.toYawPitchRoll(b.Vec3.stackCeil.set()),i=0,i=0;if(p.y>a.cameraPitchMax&&0<h||p.y<a.cameraPitchMin&&0>h)i=h*a.cameraPitchSpeed*c,h=f.worldMatrix.data,h=b.Vec3.stackCeil.set(-h[b.__13],0,-h[b.__33]).normalize(),
h=b.Vec3.stackCeil.set(h.z,0,-h.x),i=b.Quat4.fromAxisAngle(h,i,b.Quat4.stackCeil.set()),h=f.worldPosition.subtract(g,b.Vec3.stackCeil.set()),f.localPosition=i.multiplyVec3(h,b.Vec3.stackCeil.set()).add(g),f.update();i=e*a.cameraPitchChaseSpeed*c;e=b.Quat4.fromYawPitchRoll(i,0,0,b.Quat4.stackCeil.set());h=f.worldPosition.subtract(g,b.Vec3.stackCeil.set());f.localPosition=e.multiplyVec3(h,b.Vec3.stackCeil.set()).add(g);f.update();var e=a.cameraCharacterChaseSpeed*c,h=h.length(),d=(h-a.cameraCharacterDistanceBase)/
a.cameraCharacterDistanceMax*e,j=b.Vec3.stackCeil.set(g);j.y=0;var n=b.Vec3.stackCeil.set(f.worldPosition);n.y=0;j=j.subtract(n,b.Vec3.stackCeil.set());n=j.normalize(b.Vec3.stackCeil.set());(2<j.length()||0>=d)&&f.addPosition(n.scale(d));h=g.y+b.math.sin(a.cameraPitchBase)*h-f.worldPosition.y;f.addPosition(b.Vec3.stackCeil.set(0,h*e*b.math.abs(h/100),0));f.update();b.isNull(l)||(e=b.Vec3.stackCeil.set(0),l.projectPoint(f.worldPosition,e),e.x=f.worldPosition.x,e.y=b.math.max(e.y+1,f.worldPosition.y),
e.z=f.worldPosition.z,f.setPosition(e));p=b.Quat4.fromYawPitchRoll(p.x+i,p.y,p.z);g=b.Mat4.lookAt(f.worldPosition,g,b.Vec3.stackCeil.set(0,1,0),b.Mat4.stackCeil.set()).toQuat4(b.Quat4.stackCeil.set());p.smix(g.conjugate(),a.cameraCharacterChaseRotationSpeed*c);f.localOrientation=p;f.update()}}function J(f,c,a,g){var e=a.anim,h=e["MOVEMENT.player"],c=e["MOVEMENT.blend"],p=e["WALK.player"],i=e["STATE.blend"],d=a.movementRate,k=b.math.abs(d),n=a.runSpeed,t=a.walkToRunSpeed,e=K(a),r=C(a),o=B(a),o=k*o;
g.active?"STATE.player"!==g.active.name&&g.play("STATE.player"):console.warn("controller::active is null ;(");o>r?(g=a.weapon===m.GUN?3:4,h.isPaused()&&h.pause(!1),i.setWeights(0,0,1,0),0<d?o<t||a.weapon!=m.NONE?(a.weapon!=m.NONE?(a.weapon===m.GUN&&(c.setWeights(0,0,0,1,0),g=a.anim,h=g["MOVEMENT.blend"],i=g["GUN_FIRE.player"],d=a.timeDelta,g=h.getAnimationWeight(4),0.2<f.fire?(0==g&&(console.log("fire player > rewind && pause"),i.rewind(0),i.pause(!0)),f=3,1<g&&(f=10),100>g&&(g+=f*d),g=b.math.clamp(g,
0,100),10<g&&i.isPaused()&&i.pause(!1),h.setAnimationWeight(4,g)):(f=1-i.animationTime/i.duration,f>g?h.setAnimationWeight(4,0):h.setAnimationWeight(4,f))),a.weapon===m.HARPOON&&c.setWeights(0,0,0,0,0,1)):c.setWeights(0,1,0,0,0),p.setSpeed(o/e)):(p.setSpeed(1),a=(o-t)/(n-t),c.setWeights(a,1-a,0,0,0),h.setSpeed(1)):(c.setWeights(0,0,1,0,0),h.setSpeed(k))):(h.pause(!0),g=a.weapon===m.GUN?3:4,p=a.weapon!=m.NONE?g:0,(a.weapon==m.NONE||a.state==j.WEAPON_IDLE)&&i.setWeightSwitching(o/r,p,2),0<d?a.weapon!=
m.NONE?(a.weapon===m.GUN&&c.setWeights(0,0,0,o/r,0,0),a.weapon===m.HARPOON&&c.setWeights(0,0,0,0,0,o/r)):c.setWeights(0,o/r,0,0,0,0,0):0>d&&c.setWeights(0,0,o/r,0,0,0),h.setSpeed(1))}function V(b){b.gun?L([W,M]):b.harpoon&&L([X,M])}function K(b){return 0<b.movementRate?b.weapon==m.NONE?b.walkWithoutWeaponSpeed:b.walkWithWeaponSpeed:b.walkbackSpeed}function B(b){return 0<b.movementRate?b.weapon==m.NONE?b.runSpeed:b.walkWithWeaponSpeed:b.walkbackSpeed}function C(b){return 0<b.movementRate?b.weapon==
m.NONE?b.walkWithoutWeaponSpeed:b.walkWithWeaponSpeedMin:b.walkbackSpeedMin}function X(f,c,a,g){var e=a.anim,h=b.math.abs(a.movementRate);K(a);var d=C(a),i=B(a)*h,h=e["HARPOON_DRAW.player"],k=e["HARPOON_UNDRAW.player"],l=e["HARPOON_COMBO.player"],n=e["HARPOON.blend"],t=e["STATE.blend"],r=e["MOVEMENT.blend"],o=e["WALK.player"],e=e["RUN.player"],s=b.now()/1E3;b.self.hero.parameters.lastTriggers!==b.self.hero.triggers.length&&(a.weapon=m.HARPOON,h.rewind(0),h.pause(!0),n.setWeights(0,0,1,0));a.state!==
j.WEAPON_IDLE&&(f.direct.x=f.direct.y=0);a.state==j.WEAPON_NOT_DRAWED&&0.5>i&&(a.state=j.HARPOON_BEFORE_DRAW,a.movementToHarpoonEndTime=s,a.idleWeightBeforeDraw=t.getAnimationWeight(0));i<d&&(d=s-a.movementToHarpoonEndTime,d<=a.stateToHarpoonTime&&(i=d/a.stateToHarpoonTime,t.setWeights(a.idleWeightBeforeDraw*(1-i),null,null,null,i)));a.state==j.HARPOON_BEFORE_DRAW?(h.pause(!1),a.state=j.HARPOON_DRAWING,a.harpoonDrawStartTime=s):a.state==j.HARPOON_DRAWING&&(d=s-a.harpoonDrawStartTime,d>=n.duration&&
(a.state=j.HARPOON_DRAWED,a.harpoonDrawToIdleStartTime=s));if(a.state==j.HARPOON_DRAWED)d=s-a.harpoonDrawToIdleStartTime,d<=a.harpoonDrawToIdleTime?n.setWeightSwitching(d/a.harpoonDrawToIdleTime,2,1):(a.state=j.WEAPON_IDLE,n.setWeights(0,1,0,0),t.setWeights(0,0,0,0,1));else if(a.state==j.WEAPON_IDLE){if(0.2<f.fire&&!a.inAttack&&(a.inAttack=!0,a.state=j.HARPOON_BEFORE_ATTACK,l.pause(!0),l.rewind(0),a.temp[0]=s,a.temp[1]=n.getAnimationWeight(1)),f.harpoon)k.rewind(0),k.pause(!0),a.harpoonIdleToUnDrawStartTime=
s,a.movementWeightBeforeUnDraw=t.getAnimationWeight(2),a.state=j.HARPOON_BEFORE_UNDRAW}else a.state==j.HARPOON_BEFORE_ATTACK?(d=s-a.temp[0],d<=a.harpoonIdleToUndrawTime?n.setWeightSwitching(d/a.harpoonIdleToUndrawTime,1,0):(n.setWeights(1,0,0,0),l.pause(!1),a.state=j.HARPOON_ATTACKING)):a.state==j.HARPOON_ATTACKING?(a.manualSpeedControl=!0,a.manualSpeedRate=1.5/1.4,l.animationTime>=l.duration&&(a.manualSpeedRate=0,a.state=j.HARPOON_ATTACK_FINISHED,a.temp[0]=s)):a.state==j.HARPOON_ATTACK_FINISHED?
(d=s-a.temp[0],d<=a.harpoonIdleToUndrawTime?(a.manualSpeedControl=!1,n.setWeightSwitching(d/a.harpoonIdleToUndrawTime,0,1)):(n.setWeights(0,1,0,0),a.state=j.WEAPON_IDLE,a.inAttack=!1)):a.state==j.HARPOON_BEFORE_UNDRAW?(d=s-a.harpoonIdleToUnDrawStartTime,d<=a.harpoonIdleToUndrawTime?(i=d/a.harpoonIdleToUndrawTime,t.setWeights(a.movementWeightBeforeUnDraw*(1-i),null,null,0,i),n.setWeightSwitching(d/a.harpoonIdleToUndrawTime,1,3)):(t.setWeights(0,0,0,0,1),n.setWeights(0,0,0,1),a.harpoonUndrawStartTime=
s,a.state=j.HARPOON_UNDRAWING,k.pause(!1))):a.state==j.HARPOON_UNDRAWING?(d=s-a.harpoonUndrawStartTime,d>=n.duration&&(a.state=j.HARPOON_UNDRAWED,a.harpoonUndrawedTime=s)):a.state==j.HARPOON_UNDRAWED&&(d=s-a.harpoonUndrawedTime,d<=a.harpoonUndrawToIdleTime?(console.log("\u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0438\u043c \u0438\u0437 state::HARPOON --\> state.IDLE"),t.setWeightSwitching(d/a.harpoonUndrawToIdleTime,4,0)):(console.log("EGameHeroStates.HARPOON_UNDRAWED finished!"),t.setWeights(1,
0,0,0,0),r.setWeights(0,1,0,0,0),e.rewind(0),o.rewind(0),e.setSpeed(1),o.setSpeed(1),e.pause(!1),o.pause(!1),a.state=j.WEAPON_NOT_DRAWED,a.weapon=m.NONE,b.self.hero.triggers.pop()));a.state<j.HARPOON_BEFORE_UNDRAW&&J(f,c,a,g)}function W(f,c,a,g){var e=a.anim,d=b.math.abs(a.movementRate);K(a);var p=C(a),i=B(a)*d,d=e["GUN_DRAW.player"],k=e["GUN_DRAW.blend"],l=e["GUN_UNDRAW.player"],n=e["GUN_UNDRAW.blend"],t=e["GUN_IDLE.blend"],r=e["GUN.blend"],o=e["STATE.blend"],s=e["GUN_FIRE.blend"],v=e["GUN_FIRE.player"],
q=e["MOVEMENT.blend"],w=e["WALK.player"],e=e["RUN.player"],x=b.now()/1E3;f.forward&&1>a.gunDirection&&(a.gunDirection+=0.05);f.back&&-1<a.gunDirection&&(a.gunDirection-=0.05);var y=b.math.clamp(a.gunDirection,-1,1),u=b.math.max(y,0),D=1-b.math.abs(y),y=b.math.abs(b.math.min(y,0));b.self.hero.parameters.lastTriggers!==b.self.hero.triggers.length&&(a.weapon=m.GUN,d.rewind(0),d.pause(!0),r.setWeights(0,0,1,0));a.state!==j.WEAPON_IDLE&&(f.direct.x=f.direct.y=0);a.state==j.WEAPON_NOT_DRAWED&&0.5>i&&(console.log("getting gun..."),
a.state=j.GUN_BEFORE_DRAW,a.movementToGunEndTime=x,a.idleWeightBeforeDraw=o.getAnimationWeight(0));i<p&&(i=x-a.movementToGunEndTime,i<=a.stateToGunTime&&(p=i/a.stateToGunTime,i=1-p,console.log("state::IDLE --\> state::GUN ("+p+")"),o.setWeights(a.idleWeightBeforeDraw*i,null,null,p)));a.state==j.GUN_BEFORE_DRAW?(d.pause(!1),a.state=j.GUN_DRAWING,a.gunDrawStartTime=x):a.state==j.GUN_DRAWING&&(k.setWeights(u,D,y),i=x-a.gunDrawStartTime,i>=r.duration&&(a.state=j.GUN_DRAWED,a.gunDrawToIdleStartTime=x));
if(a.state==j.GUN_DRAWED)i=x-a.gunDrawToIdleStartTime,t.setWeights(u,D,y),i<=a.gunDrawToIdleTime?r.setWeightSwitching(i/a.gunDrawToIdleTime,2,0):(a.state=j.WEAPON_IDLE,r.setWeights(1,0,0,0));else if(a.state==j.WEAPON_IDLE){if(t.setWeights(u,D,y),0.2<f.fire&&!a.inAttack&&(a.inAttack=!0,v.rewind(0),r.setAnimationWeight(1,100*f.fire)),a.inAttack&&0.2>f.fire&&(p=1-v.animationTime/v.duration,p>r.getAnimationWeight(1)?(r.setAnimationWeight(1,0),console.log("end of fire anim"),a.inAttack=!1):r.setAnimationWeight(1,
p)),a.inAttack&&s.setWeights(u,D,y),f.gun)l.rewind(0),l.pause(!0),n.setWeights(u,D,y),a.gunIdleToUnDrawStartTime=x,a.movementWeightBeforeUnDraw=o.getAnimationWeight(2),a.state=j.GUN_BEFORE_UNDRAW}else a.state==j.GUN_BEFORE_UNDRAW?(i=x-a.gunIdleToUnDrawStartTime,i<=a.gunIdleToUndrawTime?(p=i/a.gunIdleToUndrawTime,o.setWeights(a.movementWeightBeforeUnDraw*(1-p),null,null,p),r.setWeightSwitching(i/a.gunIdleToUndrawTime,2,3)):(o.setWeights(0,0,0,1),r.setWeights(0,0,0,1),a.gunUndrawStartTime=x,a.state=
j.GUN_UNDRAWING,l.pause(!1))):a.state==j.GUN_UNDRAWING?(i=x-a.gunUndrawStartTime,n.setWeights(u,D,y),i>=r.duration&&(a.state=j.GUN_UNDRAWED,a.gunUndrawedTime=x)):a.state==j.GUN_UNDRAWED&&(i=x-a.gunUndrawedTime,i<=a.gunUndrawToIdleTime?o.setWeightSwitching(i/a.gunUndrawToIdleTime,3,0):(o.setWeights(1,0,0,0),q.setWeights(0,1,0,0,0),e.rewind(0),w.rewind(0),e.setSpeed(1),w.setSpeed(1),e.pause(!1),w.pause(!1),a.state=j.WEAPON_NOT_DRAWED,a.weapon=m.NONE,b.self.hero.triggers.pop()));a.state<j.GUN_BEFORE_UNDRAW&&
J(f,c,a,g)}function M(f,c,a){var g,e,d,j=0,i;e=f.direct.y;g=-f.direct.x;f=b.self.hero.camera.worldMatrix.data;f=b.Vec3.stackCeil.set(-f[b.__13],0,-f[b.__33]).normalize();j=c.worldMatrix.data;j=b.Vec3.stackCeil.set(j[b.__13],0,j[b.__33]).normalize();g=b.Vec2.stackCeil.set(g,e);e=(e=g.x==g.y&&0==g.x?0:b.math.abs(g.x)>b.math.abs(g.y)?b.math.sqrt(1+b.math.pow(g.y/g.x,2)):b.math.sqrt(b.math.pow(g.x/g.y,2)+1))?g.length()/e:0;g=g.normalize(b.Vec2.stackCeil.set());f=-b.math.atan2(f.z,f.x);g=b.Vec3.stackCeil.set(g.y,
0,g.x);b.Quat4.fromYawPitchRoll(f,0,0,b.Quat4.stackCeil.set()).multiplyVec3(g);d=g.dot(j);i=b.math.abs(d-1)/2;f=e*b.math.sign(d);d>a.walkBackAngleRange?(j=g.x*j.z-g.z*j.x,j=e*b.math.sign(j)*i):j=0;e=v.time-a.time;g=B(a);i=C(a)/g;0!=e&&(f=(f-a.movementRate)/e,d=b.math.exp(b.math.abs(a.movementRate)),d=a.movementDerivativeMin+(d-1)/(d+1)*a.movementDerivativeConst,f=a.movementRate+e*b.math.clamp(f,-d,d));a.manualSpeedControl&&(f=a.manualSpeedRate);d=b.math.abs(f);d<a.movementRateThreshold&&(f=0);0!=
j&&c.addRelRotationByEulerAngles(j*a.rotationSpeedMax*e,0,0);if(a.fallDown||d>=i)if(i=b.Vec3.stackCeil.set(0),d=b.Vec3.stackCeil.set(c.worldPosition),g*=f,a.fallDown&&(g=a.fallTransSpeed),c.addRelPosition(b.Vec3.stackCeil.set(0,0,g*e)),c.update(),!b.isNull(l))l.projectPoint(c.worldPosition,i),0.1<d.y-i.y?(!1==a.fallDown&&(a.fallDown=!0,a.fallTransSpeed=g,a.fallStartTime=b.now()),g=(b.now()-a.fallStartTime)/1E3*b.math.GRAVITY_CONSTANT,c.setPosition(c.worldPosition.x,c.worldPosition.y-g*e,c.worldPosition.z)):
(a.fallDown=!1,c.setPosition(i));a.rotationRate=j;a.movementRate=f;a.time=v.time;a.timeDelta=e}function L(f){f.push(U);b.self.hero.triggers.push({triggers:f,time:v.time})}function Y(){var f=b.self.hero.camera,c=P.find(0)||I(w);var a=E,d=w,e=F;d.isKeyPress(b.EKeyCodes.N1)||c&&c.buttons[b.EGamepadCodes.RIGHT_SHOULDER]?(f.lookAt(b.self.hero.head.worldPosition),a.setCamera(f)):(d.isKeyPress(b.EKeyCodes.N2)||c&&c.buttons[b.EGamepadCodes.LEFT_SHOULDER])&&a.setCamera(e);f=f.isActive()?!1:!0;if(f&&b.isNull(N)){f=
F;a=w;"undefined"===typeof c&&(c=null);d=c;"undefined"===typeof d&&(d=null);a.isKeyPress(b.EKeyCodes.RIGHT)?f.addRelRotationByEulerAngles(0,0,-0.05):a.isKeyPress(b.EKeyCodes.LEFT)&&f.addRelRotationByEulerAngles(0,0,0.05);a.isKeyPress(b.EKeyCodes.UP)?f.addRelRotationByEulerAngles(0,0.05,0):a.isKeyPress(b.EKeyCodes.DOWN)&&f.addRelRotationByEulerAngles(0,-0.05,0);z.set(0);e=!1;if(a.isKeyPress(b.EKeyCodes.D)||d&&d.buttons[b.EGamepadCodes.PAD_RIGHT])z.x=0.25,e=!0;else if(a.isKeyPress(b.EKeyCodes.A)||d&&
d.buttons[b.EGamepadCodes.PAD_LEFT])z.x=-0.25,e=!0;a.isKeyPress(b.EKeyCodes.R)?(z.y=0.25,e=!0):a.isKeyPress(b.EKeyCodes.F)&&(z.y=-0.25,e=!0);if(a.isKeyPress(b.EKeyCodes.W)||d&&d.buttons[b.EGamepadCodes.PAD_TOP])z.z=-0.25,e=!0;else if(a.isKeyPress(b.EKeyCodes.S)||d&&d.buttons[b.EGamepadCodes.PAD_BOTTOM])z.z=0.25,e=!0;e&&f.addRelPosition(z);d=f._getLastViewport().getTarget().getRenderer().getDefaultCanvas();a.isMousePress()&&a.isMouseMoved()&&(e=a.getMouseShift(),a=e.x,e=e.y,a/=d.width/10,e/=d.height/
10,f.addRelRotationByEulerAngles(-a,-e,0));c&&(a=c.axes[b.EGamepadAxis.RIGHT_ANALOGUE_HOR],c=c.axes[b.EGamepadAxis.RIGHT_ANALOGUE_VERT],0.25>b.math.abs(a)&&(a=0),0.25>b.math.abs(c)&&(c=0),(a||c)&&f.addRelRotationByEulerAngles(-a/10,-c/10,0))}var h=b.self.gamepads.find(0)||I(w),f=b.self.hero.root,c=b.self.hero.parameters,a=b.self.hero.root.getController(),d=b.self.hero.triggers.last,e=b.self.hero.controls,j=d.triggers;h.buttons[b.EGamepadCodes.SELECT]&&(c.blocked=!0);h.buttons[b.EGamepadCodes.START]&&
(c.blocked=!1);if(!c.blocked){var i=-h.axes[b.EGamepadAxis.LEFT_ANALOGUE_VERT],k=-h.axes[b.EGamepadAxis.LEFT_ANALOGUE_HOR],m=1-c.analogueButtonThreshold,k=b.math.abs(k)<c.analogueButtonThreshold?0:b.math.sign(k)*(b.math.abs(k)-c.analogueButtonThreshold)/m,i=b.math.abs(i)<c.analogueButtonThreshold?0:b.math.sign(i)*(b.math.abs(i)-c.analogueButtonThreshold)/m;e.direct.y=i;e.direct.x=k;e.forward=!!h.buttons[b.EGamepadCodes.PAD_TOP];e.back=!!h.buttons[b.EGamepadCodes.PAD_BOTTOM];e.left=!!h.buttons[b.EGamepadCodes.PAD_LEFT];
e.right=!!h.buttons[b.EGamepadCodes.PAD_RIGHT];e.dodge=!!h.buttons[b.EGamepadCodes.FACE_1];e.gun=!!h.buttons[b.EGamepadCodes.FACE_4];e.harpoon=!!h.buttons[b.EGamepadCodes.FACE_3];e.fire=h.buttons[b.EGamepadCodes.RIGHT_SHOULDER_BOTTOM];0.5<h.buttons[b.EGamepadCodes.LEFT_SHOULDER_BOTTOM]&&-1==O&&(O=setTimeout(function(){O=-1;switch(H){case u.WIREFRAME:v.getComposer().bShowTriangles=true;l.megaTexture._bColored=false;l.showMegaTexture=false;break;case u.COLORED:v.getComposer().bShowTriangles=false;l.megaTexture._bColored=
true;l.showMegaTexture=true;break;case u.COLORED_WIREFRAME:v.getComposer().bShowTriangles=true;l.megaTexture._bColored=true;l.showMegaTexture=true;break;case u.TEXTURE:v.getComposer().bShowTriangles=false;l.megaTexture._bColored=false;l.showMegaTexture=true}H==u.TEXTURE?H=u.WIREFRAME:H++},200));h=b.self.hero.triggers.length;for(i=0;i<j.length;++i)j[i](e,f,c,a,d.time);c.lastTriggers=h}b.self.keymap.update()}var d=b.EGameHeroStates||(b.EGameHeroStates={});d._map=[];d._map[0]="WEAPON_NOT_DRAWED";d.WEAPON_NOT_DRAWED=
0;d._map[1]="WEAPON_IDLE";d.WEAPON_IDLE=1;d._map[2]="GUN_BEFORE_DRAW";d.GUN_BEFORE_DRAW=2;d._map[3]="GUN_DRAWING";d.GUN_DRAWING=3;d._map[4]="GUN_DRAWED";d.GUN_DRAWED=4;d._map[5]="GUN_BEFORE_IDLE";d.GUN_BEFORE_IDLE=5;d._map[6]="GUN_BEFORE_UNDRAW";d.GUN_BEFORE_UNDRAW=6;d._map[7]="GUN_UNDRAWING";d.GUN_UNDRAWING=7;d._map[8]="GUN_UNDRAWED";d.GUN_UNDRAWED=8;d._map[9]="HARPOON_BEFORE_DRAW";d.HARPOON_BEFORE_DRAW=9;d._map[10]="HARPOON_DRAWING";d.HARPOON_DRAWING=10;d._map[11]="HARPOON_DRAWED";d.HARPOON_DRAWED=
11;d._map[12]="HARPOON_BEFORE_IDLE";d.HARPOON_BEFORE_IDLE=12;d._map[13]="HARPOON_BEFORE_UNDRAW";d.HARPOON_BEFORE_UNDRAW=13;d._map[14]="HARPOON_UNDRAWING";d.HARPOON_UNDRAWING=14;d._map[15]="HARPOON_UNDRAWED";d.HARPOON_UNDRAWED=15;d._map[16]="HARPOON_BEFORE_ATTACK";d.HARPOON_BEFORE_ATTACK=16;d._map[17]="HARPOON_ATTACKING";d.HARPOON_ATTACKING=17;d._map[18]="HARPOON_ATTACK_FINISHED";d.HARPOON_ATTACK_FINISHED=18;var j=b.EGameHeroStates,d=b.EGameHeroWeapons||(b.EGameHeroWeapons={});d._map=[];d._map[0]=
"NONE";d.NONE=0;d._map[1]="GUN";d.GUN=1;d._map[2]="HARPOON";d.HARPOON=2;var m=b.EGameHeroWeapons,z=new b.Vec3,T={id:"akra virtual gamepad",index:-1,timestamp:b.now(),axes:[],buttons:[]},q=new b.util.Progress,d=q.canvas;q.color="white";q.fontColor="white";d.style.position="absolute";d.style.left="50%";d.style.top="70%";d.style.zIndex="100000";d.style.marginTop=-q.height/2+"px";d.style.marginLeft=-q.width/2+"px";document.body.appendChild(q.canvas);q.drawText("Initializing demo");var Q=null,v=b.createEngine({renderer:{premultipliedAlpha:!1,
preserveDrawingBuffer:!0,alpha:!0},deps:{root:"../",files:[{path:"game.ara",name:"DEMO_DATA_ARCHIVE"}]},loader:{changed:function(d,c,a){d="";c.status===b.EDependenceStatuses.LOADING?d+="Loading ":c.status===b.EDependenceStatuses.UNPACKING&&(d+="Unpacking ");c.status===b.EDependenceStatuses.LOADING||c.status===b.EDependenceStatuses.UNPACKING?(d+="resource "+(c.name||b.path.info(b.path.uri(c.path).path).basename),b.isNull(a)||(d+=" ("+(100*(a.loaded/a.total)).toFixed(2)+"%)"),q.drawText(d)):c.status===
b.EDependenceStatuses.LOADED&&(q.total[c.deps.depth]=c.deps.total,q.element=c.deps.loaded,q.depth=c.deps.depth,q.draw(),"HERO_CONTROLLER"===c.name&&(Q=c.content))},loaded:function(){q.cancel();document.body.removeChild(q.canvas)}}}),N=v.getSceneManager().createUI(),A=v.getRenderer().getDefaultCanvas(),F=null,E=null,P=v.getGamepads(),w=b.controls.createKeymap(),l=null,R=null,S=v.getResourceManager(),k=v.getScene();b.self={engine:v,scene:k,camera:F,viewport:E,canvas:A,rsmgr:S,renderer:v.getRenderer(),
keymap:w,gamepads:P,terrain:null,cameras:[],activeCamera:0,cameraLight:null,voice:null,sky:null,hero:{root:null,head:null,pelvis:null,camera:null,triggers:[],controls:{direct:{x:0,y:0},forward:!1,back:!1,right:!1,left:!1,dodge:!1,gun:!1},parameters:{analogueButtonThreshold:0.25,time:0,timeDelta:0,manualSpeedControl:!1,manualSpeedRate:0,movementRate:0,movementRateThreshold:1E-4,movementSpeedMax:9,rotationSpeedMax:10,rotationRate:0,runSpeed:6,walkToRunSpeed:2.5,walkSpeed:1.8,walkbackSpeed:1.6,walkbackSpeedMin:0.5,
walkWithWeaponSpeed:1.4,walkWithWeaponSpeedMin:0.75,walkWithoutWeaponSpeed:1.8,movementDerivativeMax:1,movementDerivativeMin:0.5,movementDerivativeConst:0.5*(2*(Math.E+1)/(Math.E-1)),walkBackAngleRange:-0.85,cameraPitchChaseSpeed:10,cameraPitchSpeed:3,cameraPitchMax:-60*b.math.RADIAN_RATIO,cameraPitchMin:30*b.math.RADIAN_RATIO,cameraPitchBase:Math.PI/10,blocked:!0,lastTriggers:1,position:new b.Vec3(0),cameraCharacterDistanceBase:5,cameraCharacterDistanceMax:15,cameraCharacterChaseSpeed:25,cameraCharacterChaseRotationSpeed:5,
cameraCharacterFocusPoint:new b.Vec3(0,0.5,0),state:j.WEAPON_NOT_DRAWED,weapon:m.NONE,movementToHarpoonTime:1,stateToHarpoonTime:0.35,harpoonIdleToUndrawTime:0.15,harpoonUndrawToIdleTime:0.3,harpoonDrawToIdleTime:0.2,harpoonToStateTime:0.35,movementToHarpoonEndTime:0,harpoonDrawStartTime:0,harpoonDrawToIdleStartTime:0,harpoonIdleToUnDrawStartTime:0,harpoonUndrawedTime:0,harpoonUndrawStartTime:0,temp:[0,0,0,0],movementToGunTime:1,stateToGunTime:0.35,gunIdleToUndrawTime:0.15,gunUndrawToIdleTime:0.3,
gunDrawToIdleTime:0.2,gunToStateTime:0.35,movementToGunEndTime:0,idleWeightBeforeDraw:10,movementWeightBeforeUnDraw:10,gunDrawStartTime:0,gunDrawToIdleStartTime:0,gunIdleToUnDrawStartTime:0,gunUndrawedTime:0,gunUndrawStartTime:0,gunDirection:0,inAttack:!1,fallDown:!1,fallTransSpeed:0,fallStartTime:0,anim:{}}}};w.captureMouse(A.el);w.captureKeyboard(document);var u,d=u||(u={});d._map=[];d._map[0]="WIREFRAME";d.WIREFRAME=0;d._map[1]="COLORED";d.COLORED=1;d._map[2]="COLORED_WIREFRAME";d.COLORED_WIREFRAME=
2;d._map[3]="TEXTURE";d.TEXTURE=3;var O=-1,H=u.WIREFRAME;v.bind("depsLoaded",function(d){var c=N;"undefined"===typeof c&&(c=null);var a=null;b.isNull(c)?(c=A._pCanvas,a=document.createElement("div"),document.body.appendChild(a),a.appendChild(c),a.style.position="fixed"):(a=c.createComponent("IDE"),a.render($(document.body)));c=b.self;a=k.createCamera();a.attachToParent(k.getRootNode());a.addRelRotationByEulerAngles(-b.math.PI/5,0,0);a.addRelPosition(-8,5,11);a.update();F=c.camera=a;c=new b.render.DSViewport(F);
a=N;"undefined"===typeof a&&(a=null);A.addViewport(c);b.isNull(a)&&(A.resize(window.innerWidth,window.innerHeight),window.onresize=function(){A.resize(window.innerWidth,window.innerHeight)});E=c;c=b.self;a=!0;"undefined"===typeof a&&(a=!0);var g=k.getManager().getEngine().getResourceManager(),e=k.createTerrainROAM("Terrain"),h={};h.height=g.imagePool.findResource("TERRAIN_HEIGHT_MAP");h.normal=g.imagePool.findResource("TERRAIN_NORMAL_MAP");e.useTessellationThread=!1;e.init(h,new b.geometry.Rect3d(-250,
250,-250,250,0,150),6,4,4,"main");e.attachToParent(k.getRootNode());e.setInheritance(b.ENodeInheritance.ALL);e.setRotationByXYZAxis(-Math.PI/2,0,0);e.setPosition(11,-109,-109.85);(g=g.imagePool.findResource("MEGATEXTURE_MIN_LEVEL"))&&e.megaTexture.setMinLevelTexture(g);e.showMegaTexture=a;l=c.terrain=e;c=new b.io.Importer(v);c.loadDocument(Q);R=c.getController();c=l;a=F;e=R;"undefined"===typeof c&&(c=null);"undefined"===typeof a&&(a=null);"undefined"===typeof e&&(e=null);h=k.getManager().getEngine();
h.getResourceManager();g=G(k,"CHARACTER_MODEL");b.isNull(g)?c=null:(h.renderFrame(),h=new b.Vec3,!b.isNull(c)&&!b.isNull(a)&&c.projectPoint(g.worldPosition,h)&&(g.setPosition(h),g.setRotationByXYZAxis(0,b.math.PI,0),a.addPosition(h),a.lookAt(h)),b.isNull(e)||g.addController(e),c=g);b.self.hero.root=c;a=k.createCamera("character-camera");e=b.self.hero.root;g=e.findEntity("node-Bip001");h=e.findEntity("node-Bip001_Head");a.setInheritance(b.ENodeInheritance.NONE);a.attachToParent(e);a.setProjParams(Math.PI/
4,A.width/A.height,0.1,3E3);a.setRelPosition(b.Vec3.stackCeil.set(0,2.5,-5));b.self.hero.camera=a;b.self.hero.head=h;b.self.hero.pelvis=g;var j=c,c=function(a,b){i.anim[b||a]=j.getController().findAnimation(a);return i.anim[b||a]},i=b.self.hero.parameters,a=b.self.hero.root;i.time=b.self.engine.time;i.position.set(a.worldPosition);c("MOVEMENT.player");c("MOVEMENT.blend");c("STATE.player");c("STATE.blend");c("RUN.player");c("WALK.player");c("GUN.blend");c("HARPOON.blend");var e=c("HARPOON_COMBO.player"),
g=c("HARPOON_DRAW.player"),h=c("HARPOON_UNDRAW.player"),m=c("GUN_DRAW.player");c("GUN_DRAW.blend");var u=c("GUN_UNDRAW.player");c("GUN_UNDRAW.blend");c("GUN_IDLE.player");c("GUN_IDLE.blend");var n=c("GUN_FIRE.player");c("GUN_FIRE.blend");var t=a.findEntity("node-pistol_in_r_hand"),r=a.findEntity("node-Dummy01"),o=a.findEntity("node-Dummy06"),s=[a.findEntity("node-Mesh04").child,a.findEntity("node-Mesh05").child,a.findEntity("node-Mesh06").child],q=[a.findEntity("node-Mesh002").child,a.findEntity("node-Mesh003").child,
a.findEntity("node-Mesh07").child];s.forEach(function(a){a.visible=false});m.useLoop(!1);u.useLoop(!1);g.useLoop(!1);h.useLoop(!1);e.useLoop(!1);t.attachToParent(r);if(b.isDefAndNotNull(m)){var z=15/46*m.duration;m.bind("enterFrame",function(a,b,c){c<z?t.attachToParent(r):t.attachToParent(o)})}if(b.isDefAndNotNull(u)){var C=21/53*u.duration;u.bind("enterFrame",function(a,b,c){c<C?t.attachToParent(o):t.attachToParent(r)})}n.setSpeed(1);b.isDefAndNotNull(n)&&n.bind("enterFrame",function(){});if(b.isDefAndNotNull(g)){var x=
29/75*g.duration;g.bind("enterFrame",function(a,b,c){c<x?q.forEach(function(a,b){q[b].visible=true;s[b].visible=false}):q.forEach(function(a,b){q[b].visible=false;s[b].visible=true})})}if(b.isDefAndNotNull(h)){var y=44/70*h.duration;h.bind("enterFrame",function(a,b,c){c<y?q.forEach(function(a,b){q[b].visible=false;s[b].visible=true}):q.forEach(function(a,b){q[b].visible=true;s[b].visible=false})})}c("MOVEMENT.blend").setWeights(0,1,0,0,0,0);c("STATE.blend").setWeights(1,0,0,0,0);L([M,J,V]);c=G(k,
"CLOSED_BOX");c.scale(0.25);a=l;e=new b.Vec3(-2,-3.85,-5);b.isDef(e)||(e=c.worldPosition);g=new b.Vec3;a.projectPoint(e,g)&&c.setPosition(g);c.addPosition(new b.Vec3(0,1,0));c=G(k,"BARREL");c.scale(0.75);c.setPosition(new b.Vec3(-30,-40.23,-15));c.setRotationByXYZAxis(-17*b.math.RADIAN_RATIO,-8*b.math.RADIAN_RATIO,-15*b.math.RADIAN_RATIO);c=G(k,"TUBE");c.scale(19);c.setRotationByXYZAxis(0*b.math.RADIAN_RATIO,-55*b.math.RADIAN_RATIO,0);c.setPosition(new b.Vec3(-16,-52.17,-66));c=G(k,"TUBE_BETWEEN_ROCKS");
c.scale(2);c.setRotationByXYZAxis(5*b.math.RADIAN_RATIO,100*b.math.RADIAN_RATIO,0);c.setPosition(new b.Vec3(-55,-12.15,-82));c.explore(function(a){if(b.scene.isModel(a))a.mesh.shadow=false});k.bind("beforeUpdate",Y);var c=b.self,B=[];k.getRootNode().explore(function(a){b.scene.objects.isCamera(a)&&!b.scene.light.isShadowCaster(a)&&B.push(a);return true});c.cameras=B;b.self.activeCamera=b.self.cameras.indexOf(b.self.camera);c=E;a=S.createTexture(".sky-box-texture");a.loadResource("SKYBOX");c.type===
b.EViewportTypes.DSVIEWPORT&&c.setSkybox(a);c=b.self;a=14;"undefined"===typeof a&&(a=14);e=k.getManager().getEngine();e=new b.model.Sky(e,32,32,1E3);e.setTime(a);e.skyDome.attachToParent(k.getRootNode());c.sky=e;c=k.createSprite("sprite");c.attachToParent(k.getRootNode());c.setPosition(0,-1,0);c.setTexture(E._pDeferredDepthTexture);c=k.createLightPoint(b.ELightTypes.PROJECT,!0,512);c.attachToParent(k.getRootNode());c.enabled=!1;a=c.params;a.ambient.set(0,0,0,1);a.diffuse.set(1);a.specular.set(1);
a.attenuation.set(0.5,0,0);c.setPosition(new b.Vec3(-300,300,-300));c.lookAt(new b.Vec3(0,0,0));c.lightingDistance=1E4;w.bind("equalsign",function(){b.self.activeCamera++;if(b.self.activeCamera===b.self.cameras.length)b.self.activeCamera=0;E.setCamera(b.self.cameras[b.self.activeCamera])});w.bind("M",function(){d.getComposer().bShowTriangles=!d.getComposer().bShowTriangles});w.bind("N",function(){l.megaTexture&&(l.megaTexture._bColored=!l.megaTexture._bColored)});w.bind("SPACE",function(){d.isActive()?
d.pause():d.play()});c=a=!0;e=void 0;"undefined"===typeof a&&(a=!1);"undefined"===typeof c&&(c=!1);"undefined"===typeof e&&(e=100);g=b.util.createQuad(k,5*e);g.attachToParent(k.getRootNode());g.mesh.getSubset(0).setVisible(!a);a=b.util.createSceneSurface(k,e);a.addPosition(0,-0.01,0);a.attachToParent(k.getRootNode());a.mesh.getSubset(0).setVisible(!c);d.exec()})})(akra||(akra={}));
