


/*---------------------------------------------
 * assembled at: Tue Dec 24 2013 21:15:03 GMT+0400 (Московское время (зима))
 * directory: tests/common/game/RELEASE/
 * file: tests/common/game/lab4.ts
 * name: lab4
 *--------------------------------------------*/


'use strict';var __extends=this.__extends||function(a,d){function c(){this.constructor=a}c.prototype=d.prototype;a.prototype=new c},akra;
(function(a){(a.util||(a.util={})).navigation=function(d,c){function u(b){var l=a.Vec3.stackCeil.set(0),d=b.getCamera();if(a.ide&&a.ide.selectedObject)return l.set(a.ide.selectedObject.worldPosition),l;if(c)return l.set(c),l;b.unprojectPoint(b.actualWidth/2,b.actualHeight/2,l);l.subtract(d.worldPosition,a.Vec3.stackCeil.set()).length()>=d.farPlane&&(e.point=d.worldPosition,e.normal=d.localOrientation.multiplyVec3(a.Vec3.stackCeil.set(0,0,-1)),E.intersectRay3d(e,l)||l.set(e.normal.scale(10,a.Vec3.stackCeil.set()).add(e.point)));
return l}function p(a){var b=a.getCamera();u(a).subtract(b.worldPosition).length();return u(a).subtract(b.worldPosition).length()/5}function m(b,d,e){b=b.getCamera();d.hide(b.parent!==b.root);d=d.getCamera();e=b.worldPosition.subtract(e,a.Vec3.stackCeil.set()).normalize().scale(5.5);d.setPosition(e);d.lookAt(a.Vec3.stackCeil.set(0),b.localOrientation.multiplyVec3(a.Vec3.stackCeil.set(0,1,0)))}"undefined"===typeof c&&(c=null);var q=d.getTarget(),n=q.getRenderer().getEngine(),h=n.getSceneManager().createScene3D(".3d-box");
n.getScene();var z=n.getResourceManager().loadModel(a.DATA+"/models/ocube/cube.DAE",{shadows:!1}),n=h.createCamera();n.attachToParent(h.getRootNode());var o=h.createLightPoint(a.ELightTypes.PROJECT);o.attachToParent(n);o.setInheritance(a.ENodeInheritance.ALL);o.params.ambient.set(0,0,0,1);o.params.diffuse.set(1);o.params.specular.set(0.1);o.params.attenuation.set(0.5,0,0);var b=d.getTarget().addViewport(new a.render.DSViewport(n,0.7,0.05,0.25,0.25,100)),E=new a.geometry.Plane3d(a.Vec3.stackCeil.set(1,
0,0),a.Vec3.stackCeil.set(0),a.Vec3.stackCeil.set(0,0,1)),e=new a.geometry.Ray3d;q.onmousewheel=function(b,e,h,c){d.getCamera().addRelPosition(0,0,a.math.sign(-c)*p(d))};d.enableSupportFor3DEvent(a.E3DEventTypes.DRAGSTART|a.E3DEventTypes.DRAGSTOP);var A=new a.Vec3,g=0,r=0,B=1;d.ondragstart=function(b,e,c,h){e===a.EMouseButton.MIDDLE&&(q.setCursor("move"),A.set(b.getCamera().worldPosition),g=c,r=h,B=p(d))};d.ondragstop=function(b,d){d===a.EMouseButton.MIDDLE&&q.setCursor("auto")};d.ondragging=function(b,
d,e,c){d===a.EMouseButton.MIDDLE&&(b=b.getCamera(),e=a.Vec3.stackCeil.set(-(e-g),-(c-r),0).scale(0.05*B),b.setPosition(A.add(b.localOrientation.multiplyVec3(e),a.Vec3.stackCeil.set())))};var s=a.ERenderStateValues.SRCALPHA,w=a.ERenderStateValues.DESTALPHA;b.bind("render",function(b,d,e){b=d.getPass(e);d.isLastPass(e)&&(b.setRenderState(a.ERenderStates.ZENABLE,a.ERenderStateValues.FALSE),b.setRenderState(a.ERenderStates.BLENDENABLE,a.ERenderStateValues.TRUE),b.setRenderState(a.ERenderStates.SRCBLEND,
s),b.setRenderState(a.ERenderStates.DESTBLEND,w))});b.enableSupportFor3DEvent(a.E3DEventTypes.CLICK|a.E3DEventTypes.MOUSEOVER|a.E3DEventTypes.MOUSEOUT|a.E3DEventTypes.DRAGSTART|a.E3DEventTypes.DRAGSTOP|a.E3DEventTypes.MOUSEWHEEL);z.bind("loaded",function(){function e(M,F){k.set(u(d));var j=d.getCamera(),i=j.worldPosition.length();j.setPosition(k.add(M.normalize().scale(i),a.Vec3.stackCeil.set()));j.lookAt(k,F);j.update();m(d,b,k)}var c=z.attachToScene(h).child,A=c.mesh,E=0,n=0,k=new a.Vec3(0),g=!1,
o=new a.Vec3,p=new a.Vec3,r=new a.Quat4;d.bind("viewportCameraChanged",function(){m(d,b,k)});m(d,b,k);c.ondragstart=function(a,b,e,i,f){a=d.getCamera();E=i;n=f;g=!0;b.highlight(c,null);q.hideCursor();k.set(u(d));o.set(a.worldPosition);p.set(a.localPosition);r.set(a.localOrientation)};c.ondragstop=function(b,e){g=!1;e.getTarget().hideCursor(!1);s=a.ERenderStateValues.SRCALPHA;w=a.ERenderStateValues.DESTALPHA;e.highlight(null,null);e.touch()};c.ondragging=function(b,e,j,i,f){var b=d.getCamera(),j=k,
c=o,f=-((f-n)/100),i=-((i-E)/100);a.isNull(c)&&(c=b.worldPosition);c=c.subtract(j,a.Vec3.stackCeil.set());i=a.Quat4.fromYawPitchRoll(i,0,0,a.Quat4.stackCeil.set());b.setPosition(i.multiplyVec3(c,a.Vec3.stackCeil.set()).add(j));b.setRotation(i.multiply(r,a.Quat4.stackCeil.set()));i=a.Quat4.fromAxisAngle(b.localOrientation.multiplyVec3(a.Vec3.stackCeil.set(1,0,0)),-f);c=b.localPosition.subtract(j,a.Vec3.stackCeil.set());b.setPosition(i.multiplyVec3(c,a.Vec3.stackCeil.set()).add(j));b.setRotation(i.multiply(b.localOrientation,
a.Quat4.stackCeil.set()));m(d,e,k)};for(var I=0;I<A.length;++I){var J=A.getSubset(I);J.onmouseover=function(b,e){e.highlight(c,g?null:b);s=a.ERenderStateValues.ONE;w=a.ERenderStateValues.INVSRCALPHA};J.onmouseout=function(b,e){g?(e.highlight(c,null),s=a.ERenderStateValues.ONE,w=a.ERenderStateValues.INVSRCALPHA):(e.highlight(null,null),s=a.ERenderStateValues.SRCALPHA,w=a.ERenderStateValues.DESTALPHA)};J.onclick=function(c){d.getCamera();switch(c.name){case "submesh-0":e(a.Vec3.stackCeil.set(0,-1,0),
a.Vec3.stackCeil.set(0,0,1));console.log("bottom");break;case "submesh-1":e(a.Vec3.stackCeil.set(1,0,0),a.Vec3.stackCeil.set(0,1,0));console.log("right");break;case "submesh-2":console.log("left");e(a.Vec3.stackCeil.set(-1,0,0),a.Vec3.stackCeil.set(0,1,0));break;case "submesh-3":console.log("top");e(a.Vec3.stackCeil.set(0,1,0),a.Vec3.stackCeil.set(0,0,-1));break;case "submesh-4":console.log("front");e(a.Vec3.stackCeil.set(0,0,1),a.Vec3.stackCeil.set(0,1,0));break;case "submesh-5":e(a.Vec3.stackCeil.set(0,
0,-1),a.Vec3.stackCeil.set(0,1,0)),console.log("back")}m(d,b,k)}}})}})(akra||(akra={}));
(function(a){var d=new a.util.Progress,c=d.canvas;d.color="white";d.fontColor="white";c.style.position="absolute";c.style.left="50%";c.style.top="70%";c.style.zIndex="100000";c.style.marginTop=-d.height/2+"px";c.style.marginLeft=-d.width/2+"px";document.body.appendChild(d.canvas);d.drawText("Initializing demo");var c=a.createEngine({renderer:{premultipliedAlpha:!1,preserveDrawingBuffer:!0},loader:{changed:function(b,c,e){b="";switch(c.status){case a.EDependenceStatuses.LOADING:b+="Loading ";break;
case a.EDependenceStatuses.UNPACKING:b+="Unpacking "}switch(c.status){case a.EDependenceStatuses.LOADING:case a.EDependenceStatuses.UNPACKING:b+="resource "+a.path.info(a.path.uri(c.path).path).basename;a.isNull(e)||(b+=" ("+(100*(e.loaded/e.total)).toFixed(2)+"%)");d.drawText(b);break;case a.EDependenceStatuses.LOADED:d.total[c.deps.depth]=c.deps.total,d.element=c.deps.loaded,d.depth=c.deps.depth,d.draw()}},loaded:function(){d.cancel();document.body.removeChild(d.canvas)}},deps:{files:[{path:"grammars/HLSL.gr"}],
deps:{files:[{path:"effects/custom/arteries2.afx"},{path:"textures/arteries/AG/arteries.ara"}]}}}),u=c.getSceneManager().createUI(),p=c.getRenderer().getDefaultCanvas(),m=null,q=null,n=c.getResourceManager(),h=c.getScene(),z,o;c.bind("depsLoaded",function(b){function d(b,e){var c=a.path.info(b).filename,F=n.loadModel(b,{shadows:!1,axis:{x:{index:0,inverse:!1},y:{index:2,inverse:!1},z:{index:1,inverse:!1}}});F.bind("loaded",function(){var b=F.attachToScene(h);b.scale(0.008);b.setPosition(-0.75,1,-1);
var d=s.addFolder(c),f=d.add({mode:"edged faces"},"mode",["colored","wireframe","edged faces"]);d.add({visible:!1},"visible").onChange(function(a){b.child.mesh.getSubset(0).setVisible(a)});b.child.mesh.getSubset(0).setVisible(!1);f.onChange(function(a){switch(a){case "colored":b.child.mesh.getSubset(0).wireframe(!1);break;case "wireframe":b.child.mesh.getSubset(0).wireframe(!0,!1);break;case "edged faces":b.child.mesh.getSubset(0).wireframe(!0)}});b.child.mesh.getSubset(0).material.diffuse.set(a.util.randomColor(!0));
d.open();e&&e()})}var e=u;"undefined"===typeof e&&(e=null);var c=null;a.isNull(e)?(e=p._pCanvas,c=document.createElement("div"),document.body.appendChild(c),c.appendChild(e),c.style.position="fixed"):(c=e.createComponent("IDE"),c.render($(document.body)));m=h.createCamera();m.attachToParent(h.getRootNode());m.setPosition(4,4,3.5);m.lookAt(a.Vec3.stackCeil.set(0,1,0));window.camera=m;e=new a.render.DSViewport(m);c=u;"undefined"===typeof c&&(c=null);p.addViewport(e);a.isNull(c)&&(p.resize(window.innerWidth,
window.innerHeight),window.onresize=function(){p.resize(window.innerWidth,window.innerHeight)});q=e;a.util.navigation(q,new a.Vec3(0,1,0));var e=h,g=!0,c=!1,r=2;"undefined"===typeof g&&(g=!1);"undefined"===typeof c&&(c=!1);"undefined"===typeof r&&(r=100);var B=a.util.createQuad(e,5*r);B.attachToParent(e.getRootNode());B.mesh.getSubset(0).setVisible(!g);g=a.util.createSceneSurface(e,r);g.addPosition(0,-0.01,0);g.attachToParent(e.getRootNode());g.mesh.getSubset(0).setVisible(!c);b.exec();b=h.createLightPoint(a.ELightTypes.PROJECT);
b.attachToParent(m);b.setInheritance(a.ENodeInheritance.ALL);b.params.ambient.set(0,0,0,1);b.params.diffuse.set(1);b.params.specular.set(0.1);b.params.attenuation.set(0.5,0,0);b=a.util.lineCube(h);b.attachToParent(h.getRootNode());b.setPosition(0,1,0);for(var s=new dat.GUI,w=0.00781102*0.8,y=[],b=1;41>=b;++b)e="ar.",10>b&&(e+="0"),e+=String(b),e=n.texturePool.loadResource(e),e.setFilter(a.ETextureParameters.MIN_FILTER,a.ETextureFilters.LINEAR),e.setFilter(a.ETextureParameters.MAG_FILTER,a.ETextureFilters.LINEAR),
y.push(e);a.io.createFileDropArea(document.body,{drop:function(b,e){var c=n.colladaPool.createResource("dynamic"+a.sid());c.parse(e,{wireframe:true,debug:true});c.notifyLoaded();var c=c.attachToScene(h),d=c.findEntity("joint0");c.findEntity("joint0[mesh-container]");d.explore(function(b){if(a.scene.isJoint(b)){var e=a.util.basis(h);e.scale(0.01);b.update();e.setInheritance(a.ENodeInheritance.ALL);e.attachToParent(b)}});var j=o,i=void 0,f=void 0;typeof i==="undefined"&&(i=null);typeof f==="undefined"&&
(f=false);for(var d=a.animation.createParameter(),D,x,g=0;g<j.length;++g){x=j[g];i&&x.set(i.worldMatrix.multiplyVec4(a.Vec4.stackCeil.set(x,1)).xyz);D=a.Mat4.stackCeil.set(1);D.setTranslation(x);D=new a.animation.PositionFrame(g/(j.length-1),D);d.keyFrame(D);f&&console.log(g/(j.length-1),x.toString())}for(var k=[],m=[],l=[],j=0;j<z.length;j++){i=d.frame(j/z.length).translation;f=c.findEntity("joint"+j);x=f.localMatrix.getTranslation(a.Vec3.stackCeil.set());f.localMatrix=a.Mat4.stackCeil.set(1);f.setPosition(x);
f.update();f.setInheritance(a.ENodeInheritance.NONE);f.setPosition(f.worldPosition);f.update();k.push(new a.Vec3(f.worldPosition));m.push(new a.Vec3(i));l.push(f)}s.add({transform:0},"transform").min(0).max(1).step(0.005).onChange(function(b){for(var e=0;e<l.length;++e){var c=m[e],d=l[e],c=k[e].scale(1-b,a.Vec3.stackCeil.set()).add(c.scale(b,a.Vec3.stackCeil.set()));d.setPosition(c)}})}});var l=n.loadModel(a.DATA+"models/arteries_hp.obj",{shadows:!1,axis:{x:{index:0,inverse:!1},y:{index:2,inverse:!1},
z:{index:1,inverse:!1}}}),v=null;a.fopen(a.DATA+"/models/coord_real_ag.txt","r").read(function(b,e){var c;var d=e.split("\n");c=d[0].split(",");if(c[0]!=="Mx"||c[1]!=="My"||c[2]!=="Mz"){alert("wrong coords format: "+d[0]);c=void 0}else{a.Vec3.stackCeil.set(1.0588,-1.7443,-1.8989);parseFloat(d[d.length-2].split(",")[2]);c=[];for(var j=1;j<d.length;++j)if(!(d[j].length<3)){var i=d[j].split(",");c.push(new a.Vec3(parseFloat(i[0]),parseFloat(i[1]),parseFloat(i[2])));var i=c[j-1],f=a.Vec3.stackCeil.set();
f.x=(i.y+31.25)*0.008-1;f.z=i.x*0.008-1;f.y=i.z*0.008+1;i.set(f)}}o=c;d=h.getRootNode();j=0.01;typeof j==="undefined"&&(j=0.1);for(i=0;i<c.length;++i){var f=c[i],g=a.util.basis(h);g.attachToParent(d);g.setInheritance(a.ENodeInheritance.ALL);g.scale(j);g.setPosition(f)}});d(a.DATA+"models/tof_multislab_tra_2-tan.spline.2n_poyda.obj");d(a.DATA+"models/tof_multislab_tra_2-tan.spline_smoothed.2n.obj");d(a.DATA+"models/tof_multislab_tra_2.obj");l.bind("loaded",function(){var b=h.createNode();b.attachToParent(h.getRootNode());
v=l.attachToScene(b);v.setInheritance(a.ENodeInheritance.ALL);b.scale(0.0525);b.setPosition(0.0415,1.099,-0.026);b.update();a.fopen(a.DATA+"/models/coord4.txt","r").read(function(c,e){var d;d=e.split("\n");var f=d[0].split(",");if(f[0]!=="Mx"||f[1]!=="My"||f[2]!=="Mz"){alert("wrong coords format: "+d[0]);d=void 0}else{a.Vec3.stackCeil.set(1.0588,-1.7443,-1.8989);parseFloat(d[d.length-2].split(",")[2]);for(var f=[],g=1;g<d.length;++g)if(!(d[g].length<3)){var h=d[g].split(",");f.push(new a.Vec3(parseFloat(h[0]),
parseFloat(h[1]),parseFloat(h[2])));var h=f[g-1],k=a.Vec3.stackCeil.set();k.x=h.y;k.y=h.z;k.z=h.x;h.set(k)}d=f}for(f=0;f<d.length;++f){g=b.worldMatrix.multiplyVec4(a.Vec4.stackCeil.set(d[f],1));d[f].set(g.xyz)}z=d});var c=s.addFolder("modeled carotid artery"),e=c.add({mode:"edged faces"},"mode",["colored","wireframe","edged faces"]);c.add({visible:false},"visible").onChange(function(a){v.child.mesh.getSubset(0).setVisible(a)});v.child.mesh.getSubset(0).setVisible(false);e.onChange(function(a){switch(a){case "colored":v.child.mesh.getSubset(0).wireframe(false);
break;case "wireframe":v.child.mesh.getSubset(0).wireframe(true,false);break;case "edged faces":v.child.mesh.getSubset(0).wireframe(true)}});window.arteries_obj=b});var t=h.createSprite(),K=0,k=0,C=0,G=1,L=0,H=0;t.attachToParent(h.getRootNode());t.setRotationByXYZAxis(a.math.PI/2,0,0);t.setPosition(0,1,0);t.setTexture(y[0]);window.billboard=t;b=s.addFolder("slice");e=b.add({slice:0},"slice").min(0).max(1).step(0.005);b.add({opacity:H},"opacity").min(0).max(1).step(0.01).onChange(function(a){H=a});
e.onChange(function(b){t.setPosition(0,b*y.length*w+1,0);K=b;k=K*(y.length-1);C=a.math.floor(k);G=C+1;L=(k-C)/(G-C)});t.getRenderable().getRenderMethodDefault().effect.addComponent("akra.custom.arteries_slice");t.getRenderable().bind("beforeRender",function(a,b,c){c.setTexture("SLICE_A",y[C]);c.setTexture("SLICE_B",y[G]||null);c.setUniform("SLICE_K",L);c.setUniform("SLICE_OPACITY",H)});b=h.createCamera();b.setOrthoParams(2,2,-0.01,0.01);b.attachToParent(t);b.setInheritance(a.ENodeInheritance.ALL);
b.setPosition(0,0,0);b.setRotationByXYZAxis(a.math.PI,0,0);window.projCam=b;e=n.createTexture("slice");e.create(2048,2048,1,null,a.ETextureFlags.RENDERTARGET,0,0,a.ETextureTypes.TEXTURE_2D,a.EPixelFormats.R8G8B8);e.getBuffer().getRenderTarget().addViewport(new a.render.DSViewport(b));p.addViewport(new a.render.TextureViewport(e,0.05,0.05,256/q.actualWidth,256/q.actualHeight,5))})})(akra||(akra={}));
